version: '3.8'
services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: andrey
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres:
